### ISSUE TITLE
Error in 05-local-execution on MacOS

### ISSUE THREAD

**Issue by jamescalam** [aurelio-labs/semantic-router#206]
Trying to run `/docs/05-local-execution.ipynb` notebook on Mac throws the following error:

```
TypeError: Llama.create_chat_completion() missing 1 required positional argument: 'self'
```

When running:

```python
out = rl("what's the time in New York right now?")
print(out)
get_time(**out.function_call)
```

**Comment by bruvduroiu** [comment]
Seems like a LangChain error

**Comment by mafs12** [comment]
`llm` in `LlamaCppLLM` is set to `llama_cpp.Llama` [here](https://github.com/aurelio-labs/semantic-router/blob/main/semantic_router/llms/llamacpp.py#L44), but `create_chat_completion()` is not a class method.

**Comment by bruvduroiu** [comment]
Thanks for the spot @mafs12 , seems like this bug was introduced by #190. Working on a fix
